#pragma once
// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from web/Shared/CuarkDefs.ts by running 'crow-idl
// ...'. If you need to change this file, edit web/Shared/CuarkDefs.ts and run
// the crow-idl command again. Or, if you need to change the generation process,
// put up a pull-request to https://github.com/kevinfrei/ts-cpp-tooling
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by my-cuark-app v0.1.1

#include <charconv>
#include <cstddef>
#include <cstdint>
#include <iomanip>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <crow/json.h>

// TODO: Configure this header to be an external blob

/****
Conversion to JSON stuff
****/

// Helper stuff I need
// bool value for an enum-class to enable JSON specialization
template <typename T>
struct is_enum_class {
  static constexpr bool value =
      std::is_enum_v<T> && !std::is_convertible_v<T, int>;
};

template <typename T>
inline constexpr bool is_enum_class_v = is_enum_class<T>::value;

template <typename T>
constexpr auto underlying_cast(T e) noexcept {
  static_assert(std::is_enum_v<T>,
                "underlying_cast can only be used with enum types.");
  return static_cast<std::underlying_type_t<T>>(e);
}

/****
Conversion to JSON stuff
****/

// By default, simple stuff can be converted to json
// The enable_if_t is to prevent this version from being used by enum classes,
// which get extra validation to prevent stupidity from accidentally leaking.
template <typename T, typename Enabled = void>
struct impl_to_json {
  static inline crow::json::wvalue process(const T& value) {
    return crow::json::wvalue(value);
  }
};

template <typename T>
inline std::enable_if_t<!is_enum_class_v<T>, crow::json::wvalue> to_json(
    const T& value) {
  return impl_to_json<T>::process(value);
}

template <typename T>
inline std::enable_if_t<is_enum_class_v<T>, crow::json::wvalue> to_json(
    const T value) {
  return crow::json::wvalue(static_cast<std::underlying_type_t<T>>(value));
}

// A little extra work for string constants:

// Function to manually escape a string for JSON
inline std::string escape_json_string(std::string_view sv) {
  std::ostringstream o;
  for (char c : sv) {
    if (c == '"') {
      o << "\\\"";
    } else if (c == '\\') {
      o << "\\\\";
    } else if (c == '\b') {
      o << "\\b";
    } else if (c == '\f') {
      o << "\\f";
    } else if (c == '\n') {
      o << "\\n";
    } else if (c == '\r') {
      o << "\\r";
    } else if (c == '\t') {
      o << "\\t";
    } else if (static_cast<unsigned char>(c) < 0x20 ||
               static_cast<unsigned char>(c) > 0x7e) {
      // Escape other control characters and non-ASCII characters as \uXXXX
      o << "\\u" << std::hex << std::setw(4) << std::setfill('0')
        << static_cast<int>(static_cast<unsigned char>(c));
    } else {
      o << c;
    }
  }
  return o.str();
}

template <>
struct impl_to_json<std::string> {
  static inline crow::json::wvalue process(const std::string& value) {
    return crow::json::wvalue(escape_json_string(value));
  }
};
template <>
struct impl_to_json<char*> {
  static inline crow::json::wvalue process(const char* value) {
    return crow::json::wvalue(escape_json_string(value));
  }
};

template <>
struct impl_to_json<uint64_t> {
  static inline crow::json::wvalue process(const uint64_t& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.BigInt";
    v["@dataValue"] = std::to_string(value);
    return v;
  }
};

template <>
struct impl_to_json<int64_t> {
  static inline crow::json::wvalue process(const int64_t& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.BigInt";
    v["@dataValue"] = std::to_string(value);
    return v;
  }
};

template <>
struct impl_to_json<std::string_view> {
  static inline crow::json::wvalue process(std::string_view value) {
    return crow::json::wvalue(escape_json_string(value));
  }
};

// Vector<T> specialization
template <typename T>
struct impl_to_json<std::vector<T>> {
  static inline crow::json::wvalue process(const std::vector<T>& value) {
    crow::json::wvalue vec{std::vector<crow::json::wvalue>()};
    for (uint32_t i = 0; i < value.size(); i++) {
      vec[i] = to_json(value[i]);
    }
    return vec;
  }
};

// Handle char's specifically. Hurray dumb Javascript?
template <>
struct impl_to_json<char> {
  static inline crow::json::wvalue process(char value) {
    return crow::json::wvalue(std::string(1, value));
  }
};

template <typename... Args>
struct impl_to_json<std::tuple<Args...>> {
  using tup_type = std::tuple<Args...>;
  // Tuples in JSON are "just" arrays with the right size & types.
  // Doing that is...complicated.
  template <size_t Index, typename T>
  static inline void element_helper(const tup_type& tuple,
                                    crow::json::wvalue& container) {
    container[Index] = to_json(std::get<Index>(tuple));
  }
  // This is a compile time 'call the helper for each type' thing.
  template <size_t... Is>
  static inline void recurse_helper(const tup_type& tuple,
                                    crow::json::wvalue& json_list,
                                    std::index_sequence<Is...>) {
    ((element_helper<Is, std::tuple_element_t<Is, tup_type>>(tuple, json_list)),
     ...);
  }
  // make_index_sequence is the magic to do something different per tuple-item
  static inline crow::json::wvalue process(const std::tuple<Args...>& value) {
    crow::json::wvalue vec{std::vector<crow::json::wvalue>()};
    recurse_helper(value, vec, std::make_index_sequence<sizeof...(Args)>{});
    return vec;
  }
};

// I didn't need this for Windows, but I do for Linux/Mac because the map
// elem type is std::tuple on one, but a std::pair on the other
template <typename Iter>
inline crow::json::wvalue impl_vec_pair_to_json(const Iter& begin,
                                                const Iter& end) {
  std::vector<crow::json::wvalue> vec;
  for (auto it = begin; it != end; ++it) {
    crow::json::wvalue pair{std::vector<crow::json::wvalue>()};
    auto& [first, second] = *it;
    pair[0] = to_json(first);
    pair[1] = to_json(second);
    vec.push_back(pair);
  }
  return vec;
}

// My pickling framework sends JS Maps as this:
// {"@dataType":"freik.Map","@dataValue":[["a",1],["c",2],["b",3]]}
template <typename K, typename V>
struct impl_to_json<std::map<K, V>> {
  static inline crow::json::wvalue process(const std::map<K, V>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Map";
    v["@dataValue"] = impl_vec_pair_to_json(value.begin(), value.end());
    return v;
  }
};

template <typename K, typename V>
struct impl_to_json<std::unordered_map<K, V>> {
  static inline crow::json::wvalue process(
      const std::unordered_map<K, V>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Map";
    v["@dataValue"] = impl_vec_pair_to_json(value.begin(), value.end());
    return v;
  }
};

// My pickling framework sends JS Sets as this:
// {"@dataType":"freik.Set","@dataValue":["a", "c", "b"]}
template <typename T>
struct impl_to_json<std::unordered_set<T>> {
  static inline crow::json::wvalue process(const std::unordered_set<T>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Set";
    std::vector<T> flat;
    flat.reserve(value.size());
    flat.assign(value.begin(), value.end());
    v["@dataValue"] = to_json(flat);
    return v;
  }
};

template <typename T>
struct impl_to_json<std::set<T>> {
  static inline crow::json::wvalue process(const std::set<T>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Set";
    std::vector<T> flat;
    flat.reserve(value.size());
    flat.assign(value.begin(), value.end());
    v["@dataValue"] = to_json(flat);
    return v;
  }
};

template <typename T>
struct impl_to_json<std::optional<T>> {
  static inline crow::json::wvalue process(const std::optional<T>& value) {
    if (value.has_value()) {
      return to_json(*value);
    } else {
      return crow::json::wvalue(nullptr);
    }
  }
};

/****
Conversion from JSON stuff
****/

// By default, we can't read a random value from a json value
// (i.e. everything must be specialized) and it's easier to
// do this with a partial specialization of a struct :/
template <typename T, typename Enabled = void>
struct impl_from_json {
  static inline std::optional<T> process(const crow::json::rvalue&) {
    return std::nullopt;
  }
};

// Anything that doesn't either fully specialize this function,
// or partially (or fully...) specialize the above struct gets std::nullopt.
template <typename T>
inline std::optional<T> from_json(const crow::json::rvalue& json) {
  return impl_from_json<T>::process(json);
}

// Chars are a little weird, cuz, Javascript
template <>
inline std::optional<char> from_json<char>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = json.s();
  if (str.size() != 1) {
    return std::nullopt;
  }
  return static_cast<char>(str[0]);
}

template <>
inline std::optional<uint8_t> from_json<uint8_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint8_t>(json.u());
}

template <>
inline std::optional<int8_t> from_json<int8_t>(const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int8_t>(json.u());
}

template <>
inline std::optional<uint16_t> from_json<uint16_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint16_t>(json.u());
}

template <>
inline std::optional<int16_t> from_json<int16_t>(
    const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int16_t>(json.u());
}

template <>
inline std::optional<uint32_t> from_json<uint32_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint32_t>(json.u());
}

template <>
inline std::optional<int32_t> from_json<int32_t>(
    const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int32_t>(json.u());
}

template <>
inline std::optional<uint64_t> from_json<uint64_t>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Object || json.size() != 2) {
    return std::nullopt;
  }
  if (json["@dataType"].s() != "freik.BigInt") {
    return std::nullopt;
  }
  auto dataValue = json["@dataValue"];
  if (dataValue.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = dataValue.s();
  return std::stoull(str);
}

template <>
inline std::optional<int64_t> from_json<int64_t>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Object || json.size() != 2) {
    return std::nullopt;
  }
  if (json["@dataType"].s() != "freik.BigInt") {
    return std::nullopt;
  }
  auto dataValue = json["@dataValue"];
  if (dataValue.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = dataValue.s();
  return std::stoll(str);
}

template <>
inline std::optional<float> from_json<float>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Number) {
    return std::nullopt;
  }
  return static_cast<float>(json.d());
}

template <>
inline std::optional<double> from_json<double>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Number) {
    return std::nullopt;
  }
  return static_cast<double>(json.d());
}

template <>
inline std::optional<bool> from_json<bool>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::True &&
      json.t() != crow::json::type::False) {
    return std::nullopt;
  }
  return json.t() == crow::json::type::True;
}

template <>
inline std::optional<std::string> from_json<std::string>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::String) {
    return std::nullopt;
  }
  return std::string(json.s());
}

// std::vector specialization:
template <typename T>
struct impl_from_json<std::vector<T>> {
  using value_type = T;
  static inline std::optional<std::vector<value_type>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::List) {
      return std::nullopt;
    }
    std::vector<value_type> vec;
    vec.reserve(json.size());
    for (size_t i = 0; i < json.size(); i++) {
      auto item = from_json<value_type>(json[i]);
      if (!item) {
        return std::nullopt;
      }
      vec.push_back(*item);
    }
    return vec;
  }
};

// std::tuple specialization:
// TODO: Explain this, as it is rather messsy.
template <typename... Args>
struct impl_from_json<std::tuple<Args...>> {
 private:
  using tup_type = std::tuple<Args...>;
  template <size_t Index, typename T>
  static inline std::optional<T> element_helper(
      tup_type& tuple, bool& failed, const crow::json::rvalue& container) {
    std::optional<T> res = from_json<T>(container[Index]);
    failed = failed || !res.has_value();
    if (res.has_value()) {
      std::get<Index>(tuple) = res.value();
    }
    return res;
  }

  template <size_t... Is>
  static inline std::optional<tup_type> recurse(
      const crow::json::rvalue& container, std::index_sequence<Is...>) {
    tup_type res;
    bool failed = false;
    ((element_helper<Is, std::tuple_element_t<Is, tup_type>>(
         res, failed, container)),
     ...);
    if (failed)
      return std::nullopt;
    return res;
  }

 public:
  static inline std::optional<tup_type> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::List) {
      return std::nullopt;
    }
    // Check exact tuple size
    if (json.size() != sizeof...(Args)) {
      return std::nullopt;
    }
    tup_type t;
    return recurse(json, std::make_index_sequence<sizeof...(Args)>{});
  }
};

// std::set/unordered_set specialization common code:
template <template <typename...> class SetType, typename Elem>
struct impl_set_helper_from_json {
  static inline std::optional<SetType<Elem>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::Object || json.size() != 2) {
      return std::nullopt;
    }
    if (json["@dataType"].s() != "freik.Set") {
      return std::nullopt;
    }
    auto dataValue = json["@dataValue"];
    if (dataValue.t() != crow::json::type::List) {
      return std::nullopt;
    }
    SetType<Elem> m;
    for (const auto& item : dataValue) {
      auto value = from_json<Elem>(item);
      if (!value) {
        return std::nullopt;
      }
      m.insert(*value);
    }
    return m;
  }
};

// std::set specialization
template <typename Elem>
struct impl_from_json<std::set<Elem>> {
  static inline std::optional<std::set<Elem>> process(
      const crow::json::rvalue& json) {
    return impl_set_helper_from_json<std::set, Elem>::process(json);
  }
};

// std::unordered_set specialization
template <typename Elem>
struct impl_from_json<std::unordered_set<Elem>> {
  static inline std::optional<std::unordered_set<Elem>> process(
      const crow::json::rvalue& json) {
    return impl_set_helper_from_json<std::unordered_set, Elem>::process(json);
  }
};

// std::map/unordered specialization helper:
template <template <typename...> class MapType, typename K, typename V>
struct impl_map_helper_from_json {
  static inline std::optional<MapType<K, V>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::Object || json.size() != 2) {
      return std::nullopt;
    }
    if (json["@dataType"].s() != "freik.Map") {
      return std::nullopt;
    }
    auto dataValue = json["@dataValue"];
    if (dataValue.t() != crow::json::type::List) {
      return std::nullopt;
    }
    MapType<K, V> m;
    for (const auto& item : dataValue) {
      if (item.t() != crow::json::type::List || item.size() != 2) {
        return std::nullopt;
      }
      auto key = from_json<K>(item[0]);
      auto value = from_json<V>(item[1]);
      if (!key || !value) {
        return std::nullopt;
      }
      m[*key] = *value;
    }
    return m;
  }
};

// std::map specialization
template <typename K, typename V>
struct impl_from_json<std::map<K, V>> {
  static inline std::optional<std::map<K, V>> process(
      const crow::json::rvalue& json) {
    return impl_map_helper_from_json<std::map, K, V>::process(json);
  }
};

// std::unordered_set specialization
template <typename K, typename V>
struct impl_from_json<std::unordered_map<K, V>> {
  static inline std::optional<std::unordered_map<K, V>> process(
      const crow::json::rvalue& json) {
    return impl_map_helper_from_json<std::unordered_map, K, V>::process(json);
  }
};

// Enum's, specifically for my gen'ed enum types, which include an
// 'is_valid' free function overload
template <typename T>
struct impl_from_json<T, std::enable_if_t<is_enum_class_v<T>>> {
  static inline std::optional<T> process(const crow::json::rvalue& json) {
    using IntType = std::underlying_type_t<T>;
    std::optional<IntType> underlyingValue = from_json<IntType>(json);
    if (!underlyingValue.has_value())
      return std::nullopt;
    T val = static_cast<T>(underlyingValue.value());
    // Check that the enumeration is actually defined
    if (is_valid(val))
      return val;
    return std::nullopt;
  }
};

/* Horsing around a little bit
template <typename T>
struct impl_from_json<std::optional<T>> {
  static inline std::optional<std::optional<T>> process(
      const crow::json::rvalue& json) {
    if (json.t() == crow::json::type::Null) {
      return std::nullopt;
    }
    auto val = from_json<T>(json);
    if (!val.has_value()) {
      return std::nullopt;
    }
    return val;
  }
};
*/

// TODO: End Configure this header to be an external blob

namespace Shared {

template <typename T>
constexpr std::optional<T> from_string(std::string_view str);

#pragma region string enum Keys

enum class Keys { Find, Settings, Next, Prev, Tools };

inline constexpr bool is_valid(Keys _value) {
  switch (_value) {
    case Keys::Find:
    case Keys::Settings:
    case Keys::Next:
    case Keys::Prev:
    case Keys::Tools:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(Keys _value) {
  switch (_value) {
    case Keys::Find:
      return "F";
    case Keys::Settings:
      return ",";
    case Keys::Next:
      return "Right";
    case Keys::Prev:
      return "Left";
    case Keys::Tools:
      return "L";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<Keys> from_string<Keys>(std::string_view str) {
  if (str == "F")
    return Keys::Find;
  if (str == ",")
    return Keys::Settings;
  if (str == "Right")
    return Keys::Next;
  if (str == "Left")
    return Keys::Prev;
  if (str == "L")
    return Keys::Tools;
  return std::nullopt;
}

#pragma endregion string enum Keys

#pragma region string enum StrId

enum class StrId {
  FilePath,
  FilesSelected,
  ErrNotSingleAndNotMultiple,
  ErrSingleAndMultiple,
  ViewSettings,
  ViewTools
};

inline constexpr bool is_valid(StrId _value) {
  switch (_value) {
    case StrId::FilePath:
    case StrId::FilesSelected:
    case StrId::ErrNotSingleAndNotMultiple:
    case StrId::ErrSingleAndMultiple:
    case StrId::ViewSettings:
    case StrId::ViewTools:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(StrId _value) {
  switch (_value) {
    case StrId::FilePath:
      return "File Path";
    case StrId::FilesSelected:
      return "Files Selected";
    case StrId::ErrNotSingleAndNotMultiple:
      return "Not Single and not Multiple (This is a bug!)";
    case StrId::ErrSingleAndMultiple:
      return "Both Single and Multiple (This is a bug!)";
    case StrId::ViewSettings:
      return "Settings";
    case StrId::ViewTools:
      return "Tools";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<StrId> from_string<StrId>(std::string_view str) {
  if (str == "File Path")
    return StrId::FilePath;
  if (str == "Files Selected")
    return StrId::FilesSelected;
  if (str == "Not Single and not Multiple (This is a bug!)")
    return StrId::ErrNotSingleAndNotMultiple;
  if (str == "Both Single and Multiple (This is a bug!)")
    return StrId::ErrSingleAndMultiple;
  if (str == "Settings")
    return StrId::ViewSettings;
  if (str == "Tools")
    return StrId::ViewTools;
  return std::nullopt;
}

#pragma endregion string enum StrId

#pragma region linear enum CurrentView
enum class CurrentView {
  disabled = -1,
  none = 0,
  settings = 1,
  tools = 2,
  search = 3,
};

inline constexpr bool is_valid(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
    case CurrentView::none:
    case CurrentView::settings:
    case CurrentView::tools:
    case CurrentView::search:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
      return "disabled";
    case CurrentView::none:
      return "none";
    case CurrentView::settings:
      return "settings";
    case CurrentView::tools:
      return "tools";
    case CurrentView::search:
      return "search";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(CurrentView _value) {
  switch (_value) {
    case CurrentView::disabled:
      return "-1";
    case CurrentView::none:
      return "0";
    case CurrentView::settings:
      return "1";
    case CurrentView::tools:
      return "2";
    case CurrentView::search:
      return "3";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<CurrentView> from_string<CurrentView>(
    std::string_view _str) {
  int _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  CurrentView _res = static_cast<CurrentView>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum CurrentView

#pragma region linear enum IpcCall
enum class IpcCall : std::uint8_t {
  Unknown = 0,
  ReadFromStorage = 1,
  WriteToStorage = 2,
  DeleteFromStorage = 3,
  MinimizeWindow = 4,
  MaximizeWindow = 5,
  RestoreWindow = 6,
  CloseWindow = 7,
  IsDev = 8,
  AsyncData = 9,
  MenuAction = 10,
  ShowOpenDialog = 11,
  GetFileSystemRoots = 12,
  GetNamedLocations = 13,
  GetFolderContents = 14,
};

inline constexpr bool is_valid(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
    case IpcCall::ReadFromStorage:
    case IpcCall::WriteToStorage:
    case IpcCall::DeleteFromStorage:
    case IpcCall::MinimizeWindow:
    case IpcCall::MaximizeWindow:
    case IpcCall::RestoreWindow:
    case IpcCall::CloseWindow:
    case IpcCall::IsDev:
    case IpcCall::AsyncData:
    case IpcCall::MenuAction:
    case IpcCall::ShowOpenDialog:
    case IpcCall::GetFileSystemRoots:
    case IpcCall::GetNamedLocations:
    case IpcCall::GetFolderContents:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
      return "Unknown";
    case IpcCall::ReadFromStorage:
      return "ReadFromStorage";
    case IpcCall::WriteToStorage:
      return "WriteToStorage";
    case IpcCall::DeleteFromStorage:
      return "DeleteFromStorage";
    case IpcCall::MinimizeWindow:
      return "MinimizeWindow";
    case IpcCall::MaximizeWindow:
      return "MaximizeWindow";
    case IpcCall::RestoreWindow:
      return "RestoreWindow";
    case IpcCall::CloseWindow:
      return "CloseWindow";
    case IpcCall::IsDev:
      return "IsDev";
    case IpcCall::AsyncData:
      return "AsyncData";
    case IpcCall::MenuAction:
      return "MenuAction";
    case IpcCall::ShowOpenDialog:
      return "ShowOpenDialog";
    case IpcCall::GetFileSystemRoots:
      return "GetFileSystemRoots";
    case IpcCall::GetNamedLocations:
      return "GetNamedLocations";
    case IpcCall::GetFolderContents:
      return "GetFolderContents";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(IpcCall _value) {
  switch (_value) {
    case IpcCall::Unknown:
      return "0";
    case IpcCall::ReadFromStorage:
      return "1";
    case IpcCall::WriteToStorage:
      return "2";
    case IpcCall::DeleteFromStorage:
      return "3";
    case IpcCall::MinimizeWindow:
      return "4";
    case IpcCall::MaximizeWindow:
      return "5";
    case IpcCall::RestoreWindow:
      return "6";
    case IpcCall::CloseWindow:
      return "7";
    case IpcCall::IsDev:
      return "8";
    case IpcCall::AsyncData:
      return "9";
    case IpcCall::MenuAction:
      return "10";
    case IpcCall::ShowOpenDialog:
      return "11";
    case IpcCall::GetFileSystemRoots:
      return "12";
    case IpcCall::GetNamedLocations:
      return "13";
    case IpcCall::GetFolderContents:
      return "14";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<IpcCall> from_string<IpcCall>(
    std::string_view _str) {
  std::uint8_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  IpcCall _res = static_cast<IpcCall>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum IpcCall

#pragma region numeric enum SocketMsg
enum class SocketMsg : std::uint8_t { Unknown, ContentLoaded, KeepAlive };

inline constexpr bool is_valid(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
    case SocketMsg::ContentLoaded:
    case SocketMsg::KeepAlive:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
      return "Unknown";
    case SocketMsg::ContentLoaded:
      return "ContentLoaded";
    case SocketMsg::KeepAlive:
      return "KeepAlive";
    default:
      return "<unknown>";
  }
}

// Could be itoa with a cast, but string_view's...
inline constexpr std::string_view to_string(SocketMsg _value) {
  switch (_value) {
    case SocketMsg::Unknown:
      return "0";
    case SocketMsg::ContentLoaded:
      return "1";
    case SocketMsg::KeepAlive:
      return "2";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<SocketMsg> from_string<SocketMsg>(
    std::string_view _str) {
  std::uint8_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  SocketMsg _res = static_cast<SocketMsg>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion numeric enum SocketMsg

#pragma region string enum StorageId

enum class StorageId { CurrentView, SettingValue };

inline constexpr bool is_valid(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
    case StorageId::SettingValue:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(StorageId _value) {
  switch (_value) {
    case StorageId::CurrentView:
      return "currentView";
    case StorageId::SettingValue:
      return "someSetting";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<StorageId> from_string<StorageId>(
    std::string_view str) {
  if (str == "currentView")
    return StorageId::CurrentView;
  if (str == "someSetting")
    return StorageId::SettingValue;
  return std::nullopt;
}

#pragma endregion string enum StorageId

struct MimeData {
  std::string type;
  std::string data;
};

struct FileFilterItem {
  std::string name;
  std::vector<std::string> extensions;
};

struct OpenDialogOptions {
  std::optional<bool> folder;
  std::optional<std::string> title;
  std::optional<std::string> defaultPath;
  std::optional<std::string> buttonLabel;
  std::optional<bool> multiSelections;
  std::optional<std::vector<FileFilterItem>> filters;
};
using NamedLocations = std::map<std::string, std::string>;

struct FileSystemItem {
  std::string file;
  double date;
  std::uint64_t size;
  std::string type;
};
using FolderContents = std::vector<FileSystemItem>;

} // namespace Shared
#pragma region JSON serialization for string enum Keys
template <>
inline crow::json::wvalue to_json<Shared::Keys>(Shared::Keys _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::Keys> {
  static inline std::optional<Shared::Keys> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::Keys>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum Keys
#pragma region JSON serialization for string enum StrId
template <>
inline crow::json::wvalue to_json<Shared::StrId>(Shared::StrId _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::StrId> {
  static inline std::optional<Shared::StrId> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::StrId>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum StrId
#pragma region JSON serialization for string enum StorageId
template <>
inline crow::json::wvalue to_json<Shared::StorageId>(Shared::StorageId _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::StorageId> {
  static inline std::optional<Shared::StorageId> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::StorageId>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum StorageId

#pragma region JSON serialization for object MimeData
template <>
struct impl_to_json<Shared::MimeData> {
  static inline crow::json::wvalue process(const Shared::MimeData& _value) {
    crow::json::wvalue _res;
    _res["type"] = to_json(_value.type);
    _res["data"] = to_json(_value.data);

    return _res;
  }
};

template <>
inline std::optional<Shared::MimeData> from_json<Shared::MimeData>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MimeData _res;

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<std::string>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  if (!_value.has("data"))
    return std::nullopt;
  auto _data_opt_ = from_json<std::string>(_value["data"]);
  if (!_data_opt_.has_value())
    return std::nullopt;
  _res.data = std::move(*_data_opt_);

  return _res;
}
#pragma endregion JSON serialization for object MimeData

#pragma region JSON serialization for object FileFilterItem
template <>
struct impl_to_json<Shared::FileFilterItem> {
  static inline crow::json::wvalue process(
      const Shared::FileFilterItem& _value) {
    crow::json::wvalue _res;
    _res["name"] = to_json(_value.name);
    _res["extensions"] = to_json(_value.extensions);

    return _res;
  }
};

template <>
inline std::optional<Shared::FileFilterItem> from_json<Shared::FileFilterItem>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FileFilterItem _res;

  if (!_value.has("name"))
    return std::nullopt;
  auto _name_opt_ = from_json<std::string>(_value["name"]);
  if (!_name_opt_.has_value())
    return std::nullopt;
  _res.name = std::move(*_name_opt_);

  if (!_value.has("extensions"))
    return std::nullopt;
  auto _extensions_opt_ =
      from_json<std::vector<std::string>>(_value["extensions"]);
  if (!_extensions_opt_.has_value())
    return std::nullopt;
  _res.extensions = std::move(*_extensions_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FileFilterItem

#pragma region JSON serialization for object OpenDialogOptions
template <>
struct impl_to_json<Shared::OpenDialogOptions> {
  static inline crow::json::wvalue process(
      const Shared::OpenDialogOptions& _value) {
    crow::json::wvalue _res;

    if (_value.folder) {
      _res["folder"] = to_json(*_value.folder);
    }
    if (_value.title) {
      _res["title"] = to_json(*_value.title);
    }
    if (_value.defaultPath) {
      _res["defaultPath"] = to_json(*_value.defaultPath);
    }
    if (_value.buttonLabel) {
      _res["buttonLabel"] = to_json(*_value.buttonLabel);
    }
    if (_value.multiSelections) {
      _res["multiSelections"] = to_json(*_value.multiSelections);
    }
    if (_value.filters) {
      _res["filters"] = to_json(*_value.filters);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::OpenDialogOptions>
from_json<Shared::OpenDialogOptions>(const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::OpenDialogOptions _res;

  if (_value.has("folder")) {
    auto _folder_opt_ = from_json<bool>(_value["folder"]);
    if (!_folder_opt_.has_value())
      return std::nullopt;
    _res.folder = std::move(*_folder_opt_);
  } else {
    _res.folder = std::nullopt;
  }

  if (_value.has("title")) {
    auto _title_opt_ = from_json<std::string>(_value["title"]);
    if (!_title_opt_.has_value())
      return std::nullopt;
    _res.title = std::move(*_title_opt_);
  } else {
    _res.title = std::nullopt;
  }

  if (_value.has("defaultPath")) {
    auto _defaultPath_opt_ = from_json<std::string>(_value["defaultPath"]);
    if (!_defaultPath_opt_.has_value())
      return std::nullopt;
    _res.defaultPath = std::move(*_defaultPath_opt_);
  } else {
    _res.defaultPath = std::nullopt;
  }

  if (_value.has("buttonLabel")) {
    auto _buttonLabel_opt_ = from_json<std::string>(_value["buttonLabel"]);
    if (!_buttonLabel_opt_.has_value())
      return std::nullopt;
    _res.buttonLabel = std::move(*_buttonLabel_opt_);
  } else {
    _res.buttonLabel = std::nullopt;
  }

  if (_value.has("multiSelections")) {
    auto _multiSelections_opt_ = from_json<bool>(_value["multiSelections"]);
    if (!_multiSelections_opt_.has_value())
      return std::nullopt;
    _res.multiSelections = std::move(*_multiSelections_opt_);
  } else {
    _res.multiSelections = std::nullopt;
  }

  if (_value.has("filters")) {
    auto _filters_opt_ =
        from_json<std::vector<Shared::FileFilterItem>>(_value["filters"]);
    if (!_filters_opt_.has_value())
      return std::nullopt;
    _res.filters = std::move(*_filters_opt_);
  } else {
    _res.filters = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object OpenDialogOptions

#pragma region JSON serialization for object FileSystemItem
template <>
struct impl_to_json<Shared::FileSystemItem> {
  static inline crow::json::wvalue process(
      const Shared::FileSystemItem& _value) {
    crow::json::wvalue _res;
    _res["file"] = to_json(_value.file);
    _res["date"] = to_json(_value.date);
    _res["size"] = to_json(_value.size);
    _res["type"] = to_json(_value.type);

    return _res;
  }
};

template <>
inline std::optional<Shared::FileSystemItem> from_json<Shared::FileSystemItem>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::FileSystemItem _res;

  if (!_value.has("file"))
    return std::nullopt;
  auto _file_opt_ = from_json<std::string>(_value["file"]);
  if (!_file_opt_.has_value())
    return std::nullopt;
  _res.file = std::move(*_file_opt_);

  if (!_value.has("date"))
    return std::nullopt;
  auto _date_opt_ = from_json<double>(_value["date"]);
  if (!_date_opt_.has_value())
    return std::nullopt;
  _res.date = std::move(*_date_opt_);

  if (!_value.has("size"))
    return std::nullopt;
  auto _size_opt_ = from_json<std::uint64_t>(_value["size"]);
  if (!_size_opt_.has_value())
    return std::nullopt;
  _res.size = std::move(*_size_opt_);

  if (!_value.has("type"))
    return std::nullopt;
  auto _type_opt_ = from_json<std::string>(_value["type"]);
  if (!_type_opt_.has_value())
    return std::nullopt;
  _res.type = std::move(*_type_opt_);

  return _res;
}
#pragma endregion JSON serialization for object FileSystemItem
